Repository schmelto/Portfolio, pull requests merged in 2021-09, with the labels that each got.

#105 Improved minor changes
  README.md
Labels: size/S

#108 fix: remove triage label
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size/XS

#111 fix: update url in lighthouse.yml
  .github/workflows/lighthouse.yml
Labels: size/XS

#112 Update Lighthouse Check to Version 4.0.0 #110
  .github/workflows/lighthouse.yml
Labels: size/XS

#113 Update lighthouse.yml
  .github/workflows/lighthouse.yml
Labels: size/S

#114 Added badges
  README.md
Labels: size/XS

#115 Added Custom Scroll Bar
  README.md
  css/styles.css
Labels: size/S

#116 update development branch with latest changes of main
  .github/workflows/lighthouse.yml
  .github/workflows/linter.yml
  .prettierignore
  README.md
  package-lock.json
  package.json
Labels: size/M

#118 feat: add custom scroll bar (#117)
  README.md
  css/styles.css
Labels: size/S
