Repository schmelto/Portfolio, pull requests merged in 2022-04, with the labels that each got.

#177 fix: remove mail form
  index.html
  js/scripts.js
Labels: size/S

#179 docs: fixed Typo & Grammar in README.md
  README.md
Labels: size/S

#181 feat: add open issues page
  api.http
  css/bootstrap.min.css
  index.html
  issues/issues.html
  js/issues.js
  package-lock.json
  package.json
Labels: size/L

#187 feat: add issue template for docs
  .github/ISSUE_TEMPLATE/docs.yml
Labels: size/S

#190 docs: remove Chatbot
  README.md
  index.html
Labels: size/XS
