Repository schmelto/Portfolio, pull requests merged in 2022-05, with the labels that each got.

#191 feat: add terminal
  css/terminal.css
  js/terminal.js
  terminal/terminal.html
Labels: size/L

#192 Terminal
  js/terminal.js
  terminal/terminal.html
Labels: size/XS

#193 Favicon Update in blog
  blog/blog.html
Labels: size/XS

#194 docs: added some text
  README.md
Labels: size/XS

#195 test 01
  README.md
Labels: size/XS

#196 test 02
  README.md
Labels: size/XS

#204 Revert "changed card-text to white to improve contrast"
  css/styles.css
Labels: size/XS

#202 added new flex-card to link to terminal page
  index.html
Labels: size/S

#206 docs: remove checkbox
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size/S

#209 feat: Add filter option
  css/blog.css
  css/issues.css
  js/issues.js
  pages/issues.html
Labels: size/L
